# Generated by Django 4.2.3 on 2023-12-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeexperience_employeeeducation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeeducation',
            name='schoolclgssc',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='yearofpassinghsc',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
