# Generated by Django 4.2.3 on 2023-12-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeeeducation_schoolclgssc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeeducation',
            name='yearofpassingssc',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
