# Generated by Django 4.2.3 on 2023-12-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employeeeducation_yearofpassingssc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeeducation',
            name='percentagessc',
            field=models.IntegerField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='schoolclgssc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
