# Generated by Django 4.2.3 on 2023-12-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employeeeducation_percentagessc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeeducation',
            name='percentagessc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='yearofpassinghsc',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
